[package]
name = "hitokoto"
version = "0.1.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "一言 https://hitokoto.cn/."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xuxiaocheng0201/hitokoto/"
documentation = "https://docs.rs/hitokoto/"

[dependencies]
uuid = { version = "^1.11", optional = true, features = ["serde"] }
serde = { version = "^1.0", optional = true }
rand = { version = "~0.8", optional = true }
bitflags = { version = "^2.6", optional = true }

[build-dependencies]
anyhow = "^1.0"
tokio = { version = "^1.43", features = ["rt-multi-thread", "macros", "fs"] }
serde = { version = "^1.0", features = ["derive"] }
reqwest = { version = "~0.12", features = ["json"] }
uuid = { version = "^1.11", features = ["serde"] }

[features]
default = ["random"]
uuid = ["dep:uuid"]
serde = ["dep:serde", "uuid?/serde"]
random = ["dep:rand", "dep:bitflags"]
