name: Test

permissions:
  contents: read

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check rust version
        run: rustup --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: |
          sudo chmod +x ./test.sh
          ./test.sh

  verify-msrv:
    name: Verify MSRV
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-msrv
        run: cargo install cargo-msrv --locked

      - name: Verify msrv
        run: cargo msrv verify
